from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from module_agent.workflow.adapters.database.model import (
    ModuleWorkflowRunModel,
)
from module_agent.workflow.lifecycle import (
    ModuleWorkflowRun,
    ModuleWorkflowRunStatus,
)


class SqlAlchemyModuleWorkflowRunRepository:
    """提供数据持久化访问能力。"""
    def __init__(self, session: AsyncSession) -> None:
        """初始化当前对象。"""
        self.session = session

    async def get(
        self,
        literature_run_id: int,
    ) -> ModuleWorkflowRun | None:
        """读取对应记录。"""
        model = await self.session.get(
            ModuleWorkflowRunModel,
            literature_run_id,
        )
        return self._to_domain(model) if model is not None else None

    async def save(
        self,
        run: ModuleWorkflowRun,
    ) -> ModuleWorkflowRun:
        """保存当前记录。"""
        values = {
            "trace_id": run.trace_id,
            "status": run.status.value,
            "deadline_at": run.deadline_at,
            "cancellation_requested_at": (
                run.cancellation_requested_at
            ),
            "finished_at": run.finished_at,
            "error": run.error,
        }
        model = await self.session.get(
            ModuleWorkflowRunModel,
            run.literature_run_id,
        )
        if model is None:
            model = ModuleWorkflowRunModel(
                literature_run_id=run.literature_run_id,
                **values,
            )
            self.session.add(model)
        else:
            for name, value in values.items():
                setattr(model, name, value)

        await self.session.flush()
        # ``updated_at`` is generated by PostgreSQL on UPDATE. Refresh the
        # instance explicitly so domain conversion never triggers implicit
        # async I/O through an expired ORM attribute.
        await self.session.refresh(model)
        return self._to_domain(model)

    @staticmethod
    def _to_domain(model: ModuleWorkflowRunModel) -> ModuleWorkflowRun:
        return ModuleWorkflowRun(
            literature_run_id=model.literature_run_id,
            trace_id=model.trace_id,
            status=ModuleWorkflowRunStatus(model.status),
            deadline_at=model.deadline_at,
            cancellation_requested_at=(
                model.cancellation_requested_at
            ),
            created_at=model.created_at,
            updated_at=model.updated_at,
            finished_at=model.finished_at,
            error=model.error,
        )


class TransactionalModuleWorkflowRunRepository:
    """Keep workflow control state visible outside request transactions."""

    def __init__(
        self,
        session_factory: async_sessionmaker[AsyncSession],
    ) -> None:
        """初始化当前对象。"""
        self.session_factory = session_factory

    async def get(
        self,
        literature_run_id: int,
    ) -> ModuleWorkflowRun | None:
        """读取对应记录。"""
        async with self.session_factory() as session:
            repository = SqlAlchemyModuleWorkflowRunRepository(session)
            return await repository.get(literature_run_id)

    async def save(
        self,
        run: ModuleWorkflowRun,
    ) -> ModuleWorkflowRun:
        """保存当前记录。"""
        async with self.session_factory() as session:
            async with session.begin():
                repository = SqlAlchemyModuleWorkflowRunRepository(
                    session
                )
                return await repository.save(run)
