"""create paper selections

Revision ID: 1594c04479a1
Revises: e2a9c6451b7f
Create Date: 2026-09-16 12:17:53.948473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1594c04479a1'
down_revision: Union[str, Sequence[str], None] = 'e2a9c6451b7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_selections',
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('selected_paper_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('code_requirements', sa.Text(), nullable=True),
    sa.Column('selected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['literature_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_selections')
    # ### end Alembic commands ###
