"""allow ambiguous venue aliases

Revision ID: 5a929811335f
Revises: 918e52be267e
Create Date: 2026-08-26 16:50:04.857629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a929811335f'
down_revision: Union[str, Sequence[str], None] = '918e52be267e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('venue_aliases_normalized_alias_key'), 'venue_aliases', type_='unique')
    op.create_index('ix_venue_aliases_normalized_alias', 'venue_aliases', ['normalized_alias'], unique=False)
    op.create_unique_constraint('uq_venue_alias_per_venue', 'venue_aliases', ['venue_id', 'normalized_alias'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_venue_alias_per_venue', 'venue_aliases', type_='unique')
    op.drop_index('ix_venue_aliases_normalized_alias', table_name='venue_aliases')
    op.create_unique_constraint(op.f('venue_aliases_normalized_alias_key'), 'venue_aliases', ['normalized_alias'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
