"""create literature runs

Revision ID: 6c169340de9a
Revises: de0529b5f1a9
Create Date: 2026-08-27 16:05:02.620428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c169340de9a'
down_revision: Union[str, Sequence[str], None] = 'de0529b5f1a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    literature_run_status = postgresql.ENUM(
        'pending',
        'queued',
        'running',
        'completed',
        'failed',
        'cancelled',
        name='literature_run_status',
        create_type=False,
    )
    literature_run_status.create(op.get_bind(), checkfirst=True)
    op.create_table('literature_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('status', literature_run_status, nullable=False),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('search_queries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_literature_runs_status'), 'literature_runs', ['status'], unique=False)
    op.create_table('literature_run_papers',
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('paper_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['literature_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'paper_id'),
    sa.UniqueConstraint('run_id', 'position', name='uq_literature_run_paper_position')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('literature_run_papers')
    op.drop_index(op.f('ix_literature_runs_status'), table_name='literature_runs')
    op.drop_table('literature_runs')
    postgresql.ENUM(
        name='literature_run_status',
        create_type=False,
    ).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
