"""distinguish venue names by type

Revision ID: 8667ab2560ac
Revises: 5a929811335f
Create Date: 2026-08-26 16:52:48.377691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8667ab2560ac'
down_revision: Union[str, Sequence[str], None] = '5a929811335f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('venues_normalized_name_key'), 'venues', type_='unique')
    op.create_index('ix_venues_normalized_name', 'venues', ['normalized_name'], unique=False)
    op.create_unique_constraint('uq_venue_name_type', 'venues', ['normalized_name', 'venue_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_venue_name_type', 'venues', type_='unique')
    op.drop_index('ix_venues_normalized_name', table_name='venues')
    op.create_unique_constraint(op.f('venues_normalized_name_key'), 'venues', ['normalized_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
