"""create venue catalog tables

Revision ID: 918e52be267e
Revises: 4a14e4bc69e9
Create Date: 2026-08-26 13:11:23.428615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '918e52be267e'
down_revision: Union[str, Sequence[str], None] = '4a14e4bc69e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('venue_type', sa.Enum('conference', 'journal', name='venue_type'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name')
    )
    op.create_table('venue_aliases',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('venue_id', sa.BigInteger(), nullable=False),
    sa.Column('alias', sa.String(length=500), nullable=False),
    sa.Column('normalized_alias', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_alias')
    )
    op.create_index(op.f('ix_venue_aliases_venue_id'), 'venue_aliases', ['venue_id'], unique=False)
    op.create_table('venue_rankings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('venue_id', sa.BigInteger(), nullable=False),
    sa.Column('ranking_system', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('edition_year', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'ranking_system', 'edition_year', 'category', name='uq_venue_ranking_edition_category', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_venue_rankings_venue_id'), 'venue_rankings', ['venue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venue_rankings_venue_id'), table_name='venue_rankings')
    op.drop_table('venue_rankings')
    op.drop_index(op.f('ix_venue_aliases_venue_id'), table_name='venue_aliases')
    op.drop_table('venue_aliases')
    op.drop_table('venues')
    # ### end Alembic commands ###
