"""create papers table

Revision ID: de0529b5f1a9
Revises: b7c4e907cdd1
Create Date: 2026-08-27 14:43:49.717038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de0529b5f1a9'
down_revision: Union[str, Sequence[str], None] = 'b7c4e907cdd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=500), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('publication_type', sa.String(length=100), nullable=True),
    sa.Column('venue_id', sa.BigInteger(), nullable=True),
    sa.Column('venue_name', sa.String(length=500), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('landing_page_url', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('open_access_status', sa.String(length=50), nullable=True),
    sa.Column('is_open_access', sa.Boolean(), nullable=False),
    sa.Column('cited_by_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_paper_source_source_id')
    )
    op.create_index(op.f('ix_papers_venue_id'), 'papers', ['venue_id'], unique=False)
    op.create_index('uq_papers_doi', 'papers', ['doi'], unique=True, postgresql_where=sa.text('doi IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_papers_doi', table_name='papers', postgresql_where=sa.text('doi IS NOT NULL'))
    op.drop_index(op.f('ix_papers_venue_id'), table_name='papers')
    op.drop_table('papers')
    # ### end Alembic commands ###
